AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-powertools-example

  Sample SAM Template for sam-powertools-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  NodeJS16BaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/16/base/npm
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /16
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  NodeJS16BaseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS16BaseFunction}"
      RetentionInDays: 30

  NodeJS16PowerToolsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/16/powertools/npm
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: nodejs16Powertools
          POWERTOOLS_METRICS_NAMESPACE: nodejs16.x
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /16/powertools
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  NodeJS16PowerToolsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS16PowerToolsFunction}"
      RetentionInDays: 30

  NodeJS16SecretFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/16/base/secret/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /16/secret
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  NodeJS16SecretLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS16SecretFunction}"
      RetentionInDays: 30

  NodeJS16ExternalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/16/base/external/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /16/external
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts
        External:
          - 'aws-sdk'

  NodeJS16ExternalLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS16ExternalFunction}"
      RetentionInDays: 30

  NodeJS16TopLevelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/16/base/toplevel/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /16/toplevel
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts
        External:
          - 'aws-sdk'

  NodeJS16TopLevelLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS16TopLevelFunction}"
      RetentionInDays: 30

  NodeJS18SecretFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/base/secret/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/secret
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  NodeJS18SecretLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS18SecretFunction}"
      RetentionInDays: 30

  NodeJS18ExternalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/base/external/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/external
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - '@aws-sdk/client-secrets-manager'

  NodeJS18ExternalLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS18ExternalFunction}"
      RetentionInDays: 30

  NodeJS18TopLevelFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/base/toplevel/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/toplevel
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref SecretsManagerSecret
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: false
        EntryPoints:
          - app.ts
        External:
          - '@aws-sdk/client-secrets-manager'
        Format: esm
        OutExtension:
          - .js=.mjs
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);

  NodeJS18TopLevelLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NodeJS18TopLevelFunction}"
      RetentionInDays: 30

  SecretsManagerSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: SecretsManagerSecret
      Description: "Super secret Lambda Secret"
      SecretString: 'Lambdas are cool'

  BaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/base/npm
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  BaseFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${BaseFunction}"
      RetentionInDays: 30

  PowertoolsLayerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/powertools/layer/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertoolsLayer
          POWERTOOLS_METRICS_NAMESPACE: sam-powertools-example
          LOG_LEVEL: INFO
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:18
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/powertools/layer
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - app.ts
        External:
          - '@aws-lambda-powertools/commons'
          - '@aws-lambda-powertools/logger'
          - '@aws-lambda-powertools/metrics'
          - '@aws-lambda-powertools/tracer'

  PowertoolsLayerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PowertoolsLayerFunction}"
      RetentionInDays: 30

  PowertoolsNPMFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/powertools/npm/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertoolsNPM
          POWERTOOLS_METRICS_NAMESPACE: sam-powertools-example
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/powertools
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  PowertoolsNPMFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PowertoolsNPMFunction}"
      RetentionInDays: 30

  PowertoolsRemoteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/powertools/remote/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertoolsRemote
          POWERTOOLS_METRICS_NAMESPACE: sam-powertools-example
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/powertools/remote
            Method: get
      Timeout: 10
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
          - app.ts

  PowertoolsRemoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PowertoolsRemoteFunction}"
      RetentionInDays: 30

  PowertoolsSecretFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/powertools/secret/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertoolsSecret
          POWERTOOLS_METRICS_NAMESPACE: sam-powertools-example
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/powertools/secret
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref PowertoolsSecret
      Timeout: 5
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        EntryPoints:
          - app.ts
        External:
          - '@aws-sdk/client-secrets-manager'
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2022"
        Sourcemap: false

  PowertoolsSecretFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PowertoolsSecretFunction}"
      RetentionInDays: 30

  PowertoolsCompleteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/nodejs/18/powertools/complete/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertoolsComplete
          POWERTOOLS_METRICS_NAMESPACE: sam-powertools-example
          LOG_LEVEL: INFO
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /18/powertools/complete
            Method: get
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref PowertoolsSecret
      Timeout: 5
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Banner:
          - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
        EntryPoints:
          - app.ts
        External:
          - '@aws-sdk/client-secrets-manager'
        Format: esm
        Minify: true
        OutExtension:
          - .js=.mjs
        Target: "es2022"
        Sourcemap: false

  PowertoolsCompleteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PowertoolsCompleteFunction}"
      RetentionInDays: 30

  ##########################################################################
  #  Secret                                                                #
  ##########################################################################
  PowertoolsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: PowertoolsSecret
      Description: "Super special secret"
      SecretString: 'Lambda powertools are cool'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
